-- 会計(経費管理)機能用テーブル。Supabase の SQL Editor で実行してください。
create table if not exists journal_entries (
  id bigint generated by default as identity primary key,
  group_id text not null,                 -- 1つの仕訳(複数行)をまとめるID
  entry_date date not null,
  description text not null default '',
  debit_account text,
  debit_sub text,                         -- 補助科目
  debit_amount bigint not null default 0,
  credit_account text,
  credit_sub text,
  credit_amount bigint not null default 0,
  kind text not null default 'normal',    -- 'normal' | 'carryover'
  created_at timestamptz default now()
);
create index if not exists journal_entries_date_idx on journal_entries (entry_date);

-- 既存テーブルと同様、anon キーからの読み書きを許可する場合
alter table journal_entries enable row level security;
create policy "journal_entries anon all" on journal_entries for all using (true) with check (true);

-- すでに作成済みの場合は、以下の2行だけ実行してください
-- alter table journal_entries add column if not exists debit_sub text;
-- alter table journal_entries add column if not exists credit_sub text;

-- 科目マスタ(勘定科目・補助科目のメンテナンス画面用)
create table if not exists accounts (
  id bigint generated by default as identity primary key,
  name text not null unique,
  type text not null,                     -- asset | liability | equity | revenue | expense
  sort_order int not null default 0
);
create table if not exists sub_accounts (
  id bigint generated by default as identity primary key,
  account text not null,                  -- 親の勘定科目名
  name text not null,
  unique (account, name)
);
-- 家事按分(経費にする割合%)。すでに sub_accounts を作成済みの場合はこの1行だけ実行してください
alter table sub_accounts add column if not exists business_ratio numeric;
alter table accounts enable row level security;
alter table sub_accounts enable row level security;
create policy "accounts anon all" on accounts for all using (true) with check (true);
create policy "sub_accounts anon all" on sub_accounts for all using (true) with check (true);

-- カード明細CSVの取込分に付ける「要確認」フラグ。すでにテーブルを作成済みの場合はこの1行だけ実行してください
alter table journal_entries add column if not exists needs_review boolean not null default false;
