-- 会計(経費管理)機能用テーブル。Supabase の SQL Editor で実行してください。
create table if not exists journal_entries (
  id bigint generated by default as identity primary key,
  group_id text not null,                 -- 1つの仕訳(複数行)をまとめるID
  entry_date date not null,
  description text not null default '',
  debit_account text,
  debit_sub text,                         -- 補助科目
  debit_amount bigint not null default 0,
  credit_account text,
  credit_sub text,
  credit_amount bigint not null default 0,
  kind text not null default 'normal',    -- 'normal' | 'carryover'
  created_at timestamptz default now()
);
create index if not exists journal_entries_date_idx on journal_entries (entry_date);

-- 既存テーブルと同様、anon キーからの読み書きを許可する場合
alter table journal_entries enable row level security;
create policy "journal_entries anon all" on journal_entries for all using (true) with check (true);

-- すでに作成済みの場合は、以下の2行だけ実行してください
-- alter table journal_entries add column if not exists debit_sub text;
-- alter table journal_entries add column if not exists credit_sub text;
